import type { Metadata } from "next";
import { AuthProvider, QueryProvider, ThemeProvider } from "@/libs";
import { Manrope } from "next/font/google";
import { FC, PropsWithChildren, ReactElement } from "react";
import "@/styles/global.css";

const manrope = Manrope({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Portofolio | Fenny",
  description: "Generated by create next app",
};

const RootLayout: FC<PropsWithChildren> = ({ children }): ReactElement => {
  return (
    <html lang="en">
      <body className={manrope.className}>
        <AuthProvider>
          <QueryProvider>
            <ThemeProvider>{children}</ThemeProvider>
          </QueryProvider>
        </AuthProvider>
      </body>
    </html>
  );
};

export default RootLayout;
